#!/usr/bin/env bash

OUTDIR="library"
RELEASES_FILE="releases.json"

function stdout() {
	echo "$@"
}

function stderr() {
	echo "$@" >&2
}

function read_dom () {
	local IFS=\>
	read -d \< ENTITY CONTENT
}

function releases_metadata() {
	curl -sL https://repo1.maven.org/maven2/com/oracle/database/jdbc/ucp/maven-metadata.xml
}

# The releases.json file is generated by extracting release information from
# https://repo1.maven.org/maven2/com/oracle/database/jdbc/ucp/maven-metadata.xml
function releases() {
	while read_dom; do
		if [[ "${ENTITY}" == "version" ]]; then
			local version; version=${CONTENT}
			local lastbit; lastbit="$(echo "$CONTENT" | cut -d. -f5)"
			if [[ -z "${lastbit}" ]]; then
				version="${CONTENT}.0"
			fi
			echo "${version}"
		fi
	done < <(releases_metadata) | sort -r --version-sort
}

function releases_filter() {
	grep -i -e "^23."
}

function releasesjsonfile() {
	while read -r version; do
		stderr "INF: Checking for release ${version}..."
		echo "{"
		echo "  \"$version\": {"
		for variant in basic basiclite; do
			echo "    \"$variant\": {"
			for arch  in x64 arm64; do
				url=$("./instantclient.sh" check --quiet --version "$version" --variant "$variant" --arch "$arch" 2>/dev/null)
				if [ -n "$url" ]; then
					echo "      \"$arch\": \"$url\"$([ "$arch" = "x64" ] && echo "," || echo "")"
				else
					echo "      \"$arch\": null$([ "$arch" = "x64" ] && echo "," || echo "")"
				fi
			done
			echo "    }$([ "$variant" = "basic" ] && echo "," || echo "")"
		done
		echo "  }"
		echo "}"
	done | jq -s 'add'
}

function dockerbakefile () {
	local version=$1
	echo "# This file is generated by \"$(basename "$0")\" script, do not edit it manually."
	echo ""
	echo "variable \"GITHUB_REPOSITORY_OWNER\" {"
	echo "  default = \"socheatsok78\""
	echo "}"
	echo ""
	echo "variable \"GITHUB_REPOSITORY\" {"
	echo "  default = \"\${GITHUB_REPOSITORY_OWNER}/docker-oracle-instantclient\""
	echo "}"
	echo ""
	echo ""
	echo "target \"docker-metadata-action\" {}"
	echo ""
	echo "target \"github-metadata-action\" {}"
	echo ""
	echo "group \"default\" {"
	echo "  targets = ["
	echo "    \"oracle-instantclient-basic\","
	echo "    \"oracle-instantclient-basiclite\","
	echo "  ]"
	echo "}"
	echo ""
	echo "target \"oracle-instantclient-basic\" {"
	echo "  inherits = ["
	echo "    \"docker-metadata-action\","
	echo "    \"github-metadata-action\","
	echo "  ]"
	echo "  args = {"
	echo "    \"VARIANT\" = \"basic\""
	echo "  }"
	echo "  platforms = ["
	echo "    \"linux/amd64\","
	if [[ "$(jq -r ".[\"$version\"].basic.arm64" "${RELEASES_FILE}")" != "null" ]]; then
		echo "    \"linux/arm64\","
	fi
	echo "  ]"
	echo "  tags = ["
	echo "    \"docker.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${version}\","
	echo "    \"ghcr.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${version}\","
	echo "    \"docker.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${version}-basic\","
	echo "    \"ghcr.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${version}-basic\","
	echo "  ]"
	echo "}"
	echo ""
	echo "target \"oracle-instantclient-basiclite\" {"
	echo "  inherits = ["
	echo "    \"docker-metadata-action\","
	echo "    \"github-metadata-action\","
	echo "  ]"
	echo "  args = {"
	echo "    \"VARIANT\" = \"basiclite\""
	echo "  }"
	echo "  platforms = ["
	echo "    \"linux/amd64\","
	if [[ "$(jq -r ".[\"$version\"].basiclite.arm64" "${RELEASES_FILE}")" != "null" ]]; then
		echo "    \"linux/arm64\","
	fi
	echo "  ]"
	echo "  tags = ["
	echo "    \"docker.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${version}-basiclite\","
	echo "    \"ghcr.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${version}-basiclite\","
	echo "  ]"
	echo "}"
}

function dockerfile () {
	local version=$1
	echo "# syntax=docker/dockerfile:1"
	echo "# This file is generated by \"$(basename "$0")\" script, do not edit it manually."
	echo ""
	echo "ARG VARIANT=basic"
	echo "FROM scratch AS instantclient-basic-amd64"
	echo "ADD $(jq -r ".[\"$version\"].basic.x64" "${RELEASES_FILE}") /instantclient-linux.zip"
	echo "FROM scratch AS instantclient-basic-arm64"
	if [[ "$(jq -r ".[\"$version\"].basic.arm64" "${RELEASES_FILE}")" != "null" ]]; then
		echo "ADD $(jq -r ".[\"$version\"].basic.arm64" "${RELEASES_FILE}") /instantclient-linux.zip"
	else
		echo "# No ARM64 artifact found for basic, skipping"
	fi
	echo ""
	echo "FROM scratch AS instantclient-basiclite-amd64"
	echo "ADD $(jq -r ".[\"$version\"].basiclite.x64" "${RELEASES_FILE}") /instantclient-linux.zip"
	echo "FROM scratch AS instantclient-basiclite-arm64"
	if [[ "$(jq -r ".[\"$version\"].basiclite.arm64" "${RELEASES_FILE}")" != "null" ]]; then
		echo "ADD $(jq -r ".[\"$version\"].basiclite.arm64" "${RELEASES_FILE}") /instantclient-linux.zip"
	else
		echo "# No ARM64 artifact found for basiclite, skipping"
	fi
	echo ""
	echo "FROM instantclient-\${VARIANT}-\${TARGETARCH} AS instantclient"
	echo ""
	echo "FROM --platform=$BUILDPLATFORM ghcr.io/socheatsok78/unzip:latest AS oic"
	echo "COPY --link --from=instantclient /instantclient-linux.zip /tmp/instantclient-linux.zip"
	echo "RUN <<EOF"
	echo -e "\tmkdir -p /opt/oracle"
	echo -e "\tunzip /tmp/instantclient-linux.zip -d /opt/oracle"
	echo -e "\tln -s /opt/oracle/instantclient_*/ /opt/oracle/instantclient"
	echo "EOF"
	echo ""
	echo "FROM scratch"
	echo "COPY --link --from=oic /opt/oracle /opt/oracle"
}

function main() {
	while [ "$#" -gt 0 ]; do
		case "$1" in
			--outdir)
				OUTDIR="$2"
				shift 2
				;;
			--overwrite)
				overwrite=true
				echo "INF: Overwrite mode enabled, existing versions will be overwritten."
				shift 1
				;;
			--generate-releases-json)
				echo "INF: Generating releases.json file..."
				# generate releases.json file in the root directory if it doesn't exist
				if [ "${overwrite}" = true ]; then
					rm -f "${RELEASES_FILE}"
				fi
				if [ ! -f "${RELEASES_FILE}" ]; then
					releases | releasesjsonfile > "${RELEASES_FILE}"
				fi
				exit 0
				;;
			*)
				echo "Usage: $0 [--overwrite] [--outdir <output directory>]"
				exit 1
				;;
		esac
	done

	if [ ! -f "${RELEASES_FILE}" ]; then
		releases | releasesjsonfile > "${RELEASES_FILE}"
	fi

	# generate files for each release
	releases | while read -r version; do
		if [ "${overwrite}" = true ]; then
			rm -rf "${OUTDIR:?}/${version}"
		fi
		if [ -d "${OUTDIR:?}/${version}" ]; then
			echo "WRN: Skipping version ${version} because it already exists."
			continue
		fi
		# if there's no artifact for this version, skip it
		if [[ "$(jq -r ".\"$version\".basic.x64" "${RELEASES_FILE}")" != "null" ]]; then
			echo "INF: Generating files for release ${version}..."
			mkdir -p "library/$version"
			dockerbakefile "$version" > "library/$version/docker-bake.hcl"
			dockerfile "$version" > "library/$version/Dockerfile"
		else
			echo "WRN: Skipping version ${version} because no artifacts were found."
		fi
	done
}

main "${@}"
